name: Run lint checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Run workflows manually 
  workflow_dispatch:

jobs:
  run_lint_checks:
    runs-on: ubuntu_latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run lint
      run: ./gradlew spotlessCheck
      
    - name: Build with Gradle
      run: ./gradlew build
